/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-surface': '#e6e2df',
        'surface-container': '#201f1e',
        'secondary': '#e0c29f',
        'error': '#ffb4ab',
        'outline': '#9c8e82',
        'tertiary-container': '#aaaf96',
        'surface-container-lowest': '#0f0e0d',
        'surface-container-high': '#2b2a29',
        'inverse-on-surface': '#32302f',
        'secondary-container': '#5a452b',
        'primary-fixed-dim': '#f0bd8b',
        'on-tertiary-fixed-variant': '#444935',
        'on-primary-fixed': '#2c1600',
        'on-primary-fixed-variant': '#623f18',
        'on-background': '#e6e2df',
        'tertiary': '#c6cab1',
        'on-secondary-container': '#d1b492',
        'background': '#141312',
        'surface-bright': '#3a3938',
        'on-tertiary': '#2e3220',
        'surface-container-low': '#1c1b1a',
        'surface-tint': '#f0bd8b',
        'primary-container': '#d4a373',
        'on-tertiary-fixed': '#191d0d',
        'inverse-surface': '#e6e2df',
        'surface-container-highest': '#363433',
        'on-secondary-fixed-variant': '#584329',
        'secondary-fixed': '#fdddb9',
        'surface': '#141312',
        'surface-dim': '#141312',
        'on-surface-variant': '#d4c4b7',
        'secondary-fixed-dim': '#e0c29f',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'on-primary': '#482904',
        'outline-variant': '#50453b',
        'on-primary-container': '#5b3912',
        'primary': '#f2be8c',
        'on-secondary-fixed': '#281803',
        'tertiary-fixed-dim': '#c4c9b0',
        'error-container': '#93000a',
        'tertiary-fixed': '#e0e5cb',
        'primary-fixed': '#ffdcbd',
        'on-secondary': '#3f2d14',
        'inverse-primary': '#7d562d',
        'on-tertiary-container': '#3e422f',
        'surface-variant': '#363433',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
      },
      spacing: {
        'space-md': '1rem',
        'margin-mobile': '1.25rem',
        gutter: '1.5rem',
        'space-lg': '1.5rem',
        margin: '3rem',
        'space-xl': '2.5rem',
        'space-xs': '0.25rem',
        'gutter-mobile': '1rem',
        'space-sm': '0.5rem',
      },
      fontFamily: {
        'headline-sm': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'label-code-sm': ['JetBrains Mono', 'monospace'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'label-code-md': ['JetBrains Mono', 'monospace'],
        'display-xl': ['Inter', 'sans-serif'],
        'display-xl-mobile': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-technical': ['JetBrains Mono', 'monospace'],
        'label-code': ['JetBrains Mono', 'monospace'],
        'label-metric': ['JetBrains Mono', 'monospace'],
        'headline-xl': ['Inter', 'sans-serif'],
        'display': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-sm': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'headline-lg-mobile': ['28px', { lineHeight: '34px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'label-code-sm': ['11px', { lineHeight: '16px', letterSpacing: '0.06em', fontWeight: '500' }],
        'headline-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '500' }],
        'label-code-md': ['13px', { lineHeight: '18px', letterSpacing: '0.04em', fontWeight: '500' }],
        'display-xl': ['56px', { lineHeight: '64px', letterSpacing: '-0.03em', fontWeight: '600' }],
        'display-xl-mobile': ['38px', { lineHeight: '44px', letterSpacing: '-0.025em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', letterSpacing: '-0.005em', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '24px', letterSpacing: '0', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '400' }],
        'label-technical': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'label-code': ['13px', { lineHeight: '18px', letterSpacing: '0.02em', fontWeight: '400' }],
        'label-metric': ['20px', { lineHeight: '24px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.025em', fontWeight: '600' }],
        'display': ['3.5rem', { lineHeight: '1.1', letterSpacing: '-0.03em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};