/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-lowest': '#080B12',
        'surface-container-low': '#0D111A',
        'surface-container': '#111722',
        'surface-container-high': '#18202F',
        'surface-container-highest': '#222B3D',
        surface: '#0D111A',
        background: '#080B12',
        outline: '#606D80',
        'outline-variant': '#1E2638',
        'on-surface': '#E3E9F3',
        'on-surface-variant': '#94A3B8',
        secondary: '#9BB0CE',
        primary: '#7BD0FF',
        'primary-container': '#7BD0FF',
        'on-primary-container': '#002B40',
        tertiary: '#4EDEA3',
        'status-green': '#4EDEA3',
        'status-amber': '#FFB84D',
        'status-red': '#FF6B6B',
        'status-cyan': '#7BD0FF',
        error: '#FF6B6B',
        warning: '#FFB84D',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em' }],
        'body-sm': ['12px', { lineHeight: '18px' }],
        'body-md': ['14px', { lineHeight: '22px' }],
        'body-lg': ['16px', { lineHeight: '26px' }],
        'headline-sm': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'mono-code': ['13px', { lineHeight: '20px' }],
        'mono-metric': ['22px', { lineHeight: '28px', fontWeight: '600' }],
      },
      keyframes: {
        flowArrow: {
          '0%, 100%': { opacity: '0.3', transform: 'translateX(-3px)' },
          '50%': { opacity: '1', transform: 'translateX(3px)' },
        },
        pulseGlowRed: {
          '0%, 100%': { borderColor: 'rgba(255, 107, 107, 0.4)', boxShadow: '0 0 0 0 rgba(255, 107, 107, 0.2)' },
          '50%': { borderColor: 'rgba(255, 107, 107, 0.9)', boxShadow: '0 0 14px 2px rgba(255, 107, 107, 0.25)' },
        },
        pulseGlowAmber: {
          '0%, 100%': { borderColor: 'rgba(255, 184, 77, 0.4)', boxShadow: '0 0 0 0 rgba(255, 184, 77, 0.2)' },
          '50%': { borderColor: 'rgba(255, 184, 77, 0.9)', boxShadow: '0 0 14px 2px rgba(255, 184, 77, 0.25)' },
        },
      },
      animation: {
        'flow-arrow': 'flowArrow 2s ease-in-out infinite',
        'pulse-amber': 'pulseGlowAmber 2.4s ease-in-out infinite',
        'pulse-red': 'pulseGlowRed 2.4s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};
